source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'Example', :exclusive => true do
  pod "URBNDataSource", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "URBNDataSource", :path => "../"
end
