source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Example' do
    target 'ExampleTests' do
    inherit! :search_paths
    end 
end


pod "URBNDataSource", :path => "../"
