source 'https://github.com/CocoaPods/Specs.git'

target 'URBNDataSource', :exclusive => true do
  pod "URBNDataSource", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "URBNDataSource", :path => "../"

  
end
